### PR TITLE
refactor: move top level functions as method on an API struct

### LINKED ISSUE #29: move top level functions as method on the Client struct
**Is your feature request related to a problem? Please describe.**
The way the main-level functions are organized prevents the reuse of an HTTP client and thus forces the creation of a new TCP connection for every function call.

Here is the list of the functions I talking about:
```
func GetInfo
func GetVersion
func GetDependencies
func GetProject
func GetAdvisory
func GetQuery
```
Mainly all the exported functions in this file https://github.com/edoardottt/depsdev/blob/main/pkg/depsdev/api.go

**Describe the solution you'd like**
These functions should be converted to methods on a struct that encapsulates the [Client struct](https://github.com/edoardottt/depsdev/blob/e3889fb30b0649658c42381f7a0dbc84ce24cc8b/pkg/client/client.go#L34C9-L34C9)
This way, the HTTP client would be kept between requests, which in turn would allow to re-use the TCP connection.

**Additional context**
I've run a very simple benchmark to highlight the potential gain of this change.
I've benchmarked the `GetInfo` and `GetVersion` API calls.
Here are the results:
```
goos: darwin
goarch: arm64
pkg: github.com/edoardottt/depsdev/pkg/depsdev
             │ functions.perf │             methods.perf             │
             │     sec/op     │    sec/op     vs base                │
GetInfo-8       143.66m ±  6%   78.47m ± 15%  -45.38% (p=0.000 n=10)
GetVersion-8    119.86m ± 16%   53.91m ±  6%  -55.02% (p=0.000 n=10)
geomean          131.2m         65.04m        -50.43%
```
The code of the benchmark can be found at https://github.com/zaibon/depsdev/blob/reuse-http-client/pkg/depsdev/api_test.go

### PR DESCRIPTION
**Pull request by zaibon**
fixes #29

### CODE REVIEW

**Review by edoardottt — CHANGES_REQUESTED** [review]
Great job @zaibon! thanks so much :D
some little changes needs to be carried out:
1. the README needs to be updated with new info on how to use depsdev as package
2. the code needs to be linted using `golangci-lint`

**Comment by zaibon** [comment]
@edoardottt all done :-)

**Review by edoardottt — APPROVED** [review]
lgtm!

**Comment by edoardottt** [comment]
thank you so much @zaibon ! :+1:

**Pull request merged**
