### PR TITLE
fix: rename package to match directory name

### PR DESCRIPTION
**Pull request by zaibon**

### CODE REVIEW

**Comment by edoardottt** [comment]
Hi @zaibon ! thanks for the PR. 

I was wondering.. is there a specific reason for this change?
As far as I can see the user has to use a proper name to import the module:
```golang
import (
	"testing"

	"github.com/edoardottt/depsdev/pkg/client"
	def "github.com/edoardottt/depsdev/pkg/depsdev/definitions"
	"github.com/stretchr/testify/require"
)
```

See https://github.com/edoardottt/depsdev/blob/devel/pkg/depsdev/v3/api_internal_test.go#L21


How this will change?

thanks :)

**Comment by zaibon** [comment]
Usually, the name of you package follow the name of the directory where it lives. It's not mandatory, but that's what you usually see.

At the moment, because both package are called `depsdev`. you cannot import both `"github.com/edoardottt/depsdev/pkg/depsdev/v3"` and `"github.com/edoardottt/depsdev/pkg/depsdev/v3/definitions"` without using a renamed import. 

Actually, now that I'm looking at it. the package located at `"github.com/edoardottt/depsdev/pkg/depsdev/v3"` is also called `depsdev`. I've never seen an organization like this before.

**Comment by edoardottt** [comment]
> I've never seen an organization like this before.

Suggest what you think it'd the best option :) I'm all ears!

I renamed the packages in a rush cuz I wanted to fit v3 and v3alpha in the same place.

**Comment by zaibon** [comment]
> I renamed the packages in a rush cuz I wanted to fit v3 and v3alpha in the same place.

Ok, I understand where this comes from now. 
I've had a look at the code in the `V3` and `V3Alpha` package, and at the moment the only difference seems to be the base path used when creating the `APIV3` or `APIV3alpha` struct. There is no change nor in the logic or the types used to read the responses.
So what I would do is, get rid of the V3 and V3Alpha directory and move the code into the `depsdev` directory itself.
Then, to still allow to have both version supported, just declare 2 constructors. Something like
```go
type API struct {
	client *client.Client
}

// NewV3AlphaAPI creates and returns a V3Alpha API object.
func NewV3AlphaAPI() *API {
	return &API{
		client: client.New(V3AlphaBasePath),
	}
}

// NewV3API creates and returns a V3 API object.
func NewV3API() *API {
	return &API{
		client: client.New(V3BasePath),
	}
}
``` 

This would allow you to still be able to instantiate a client for any version of the API you want to reach, but without all the duplicate code.
Regarding the imports, now that all the code lives in the `depsdev` directory, we can keep the `package depsdev` like it was, since now it would match the directory name also.

**Comment by edoardottt** [comment]
for now there is no difference, but the plan is to implement some methods only for the alpha version, check the issues. eventually they will be added to the stable version too (V3) but for now they aren't available. 
also, the Google team said that these should be maintained as two separate packages (https://github.com/google/deps.dev/issues/76).

**Comment by zaibon** [comment]
Ok, these things are bound to diverse at some point, that make sense. So let's forget this PR altogether, it doesn't really solve anything then.

**Comment by edoardottt** [comment]
fine @zaibon :) If you want to contribute...every contribution is more than welcome!

**Pull request closed without merging**
